runtime: python27
api_version: 1
threadsafe: true

runtime_config:
    python_version: 3.6

libraries:
- name: ssl
  version: latest

handlers:
- url: /(.*\.(txt|png|jpg|css|js|json))$
  static_files: static/\1
  upload: static/.*\.(txt|png|jpg|css|js|json)$
- url: /.*
  script: main.app
