runtime: python27
api_version: 1
threadsafe: true

runtime_config:
    python_version: 3.6

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app